# ==============================================================================================================================
# yamllint configuration
# ==============================================================================================================================
---
extends: default

rules:
  line-length:
    max: 128

  truthy:
    # Disable truthy warning for "on:" key in Gitdhub Actions
    check-keys: false
